.PHONY: clean All

All:
	@echo "----------Building project:[ Exercise_01 - Debug ]----------"
	@cd "Exercise_01" && "$(MAKE)" -f  "Exercise_01.mk"
clean:
	@echo "----------Cleaning project:[ Exercise_01 - Debug ]----------"
	@cd "Exercise_01" && "$(MAKE)" -f  "Exercise_01.mk" clean
