.PHONY: clean All

All:
	@echo "----------Building project:[ Exercise_06.2 - Debug ]----------"
	@cd "Exercise_06.2" && "$(MAKE)" -f  "Exercise_06.2.mk"
clean:
	@echo "----------Cleaning project:[ Exercise_06.2 - Debug ]----------"
	@cd "Exercise_06.2" && "$(MAKE)" -f  "Exercise_06.2.mk" clean
